export const Data = [
  {
    id: 1,
    name: 'Full year tuition paid',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 2,
    name: 'Full year tuition paid',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 3,
    name: 'Full year tuition paid',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 4,
    name: 'Win #250,000 monthly',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 5,
    name: 'Full year tuition paid',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 6,
    name: 'Full year tuition paid',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 7,
    name: 'Win #10,000 weekly',
    description: 'This is a weekly raffle',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 8,
    name: 'Full year tuition paid',
    description: 'Lets help your childs education',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 9,
    name: 'Full year tuition paid',
    description: 'Full year tuition paid',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
  {
    id: 10,
    name: 'Full year tuition paid',
    description: 'Lets help your childs education',
    amount: 10000,
    date: '2020-01-01',
    type: 'one-time',
    category: 'raffle draw',
  },
]